alias listalias='clear;cat ~/.bashrc'
alias ealias=' vi ~/.bashrc'
alias salias='source  ~/.bashrc'

alias apuser='sudo -s -u _www'

alias ll='ls -la'
alias cl='clear'
alias hosts='sudo vi /etc/hosts'
alias bl='brew services list'

alias gs='git status'
alias gsn='git show --pretty="" --name-only'
alias gp='git push'
alias gpup='git push --set-upstream origin '
alias gpa='git branch -r | grep -v "\->" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done && git fetch --all && git pull --all'
alias gc='git commit -m'
alias gch='git checkout'
alias gcm='git checkout master'
alias gcm2='git checkout main'
alias gforward='sourceBranch=`git branch --show-current`;git checkout master; git pull; git checkout $sourceBranch; git merge master;'
alias gpsu='git push --set-upstream origin $(git branch --show-current)'
alias ga='git add'
alias gl='git log --oneline'
alias gl2='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
alias gpl='git pull'
alias gb='git branch -v -a'
alias gd='git diff -U0'
alias gd2='git whatchanged -p '
alias gds='git diff --staged'
alias gdlc='git diff -U0 HEAD^ HEAD'
alias gdlcn='git diff -U0 $1 HEAD --name-only'
alias gdm='git diff --name-only master $(git rev-parse --abbrev-ref HEAD)'
alias gdm2='git diff master'
alias gh='git log -p'
alias gunstage='git reset --'

alias grepdir='grep -Hrn --exclude-dir=node_modules '
alias grepdir2='grep -Hrn -A 1 --exclude-dir=node_modules '
alias findfile='find . -name '
alias listssh='cat ~/.ssh/config'
alias sshconfig='sudo vi ~/.ssh/config'

alias dc='docker container'
alias dcl='docker container ls --all'
alias di='docker image'
alias dil='docker image ls'
alias dkill='docker kill'
alias dlog='function _dlog(){ docker logs $1;}; _dlog'
alias dssh='function _dssh(){ docker exec -it $1 /bin/bash;}; _dssh'
alias dssh2='function _dssh2(){ docker exec -it $1 /bin/ash;}; _dssh2'

alias listen1='netstat -an -ptcp | grep LISTEN'
alias listen2='lsof -i -P | grep -i "listen"'

alias pro='cd ~/Programming'
alias loco='pro && cd loco' 
alias mops='pro && cd mops'
alias mopsui='mops && cd ui'
alias mopsapi='mops && cd api'
alias mopgateway='mops && cd gateways'
alias gateways='mops && cd gateways'
alias e2e='mops && cd e2e-tests'
alias k='kubectl '
alias a='aws-okta '
alias aint='a select master-mops-int-OktaDev'
alias aprod='a select master-mops-prod-OktaDev'
alias k9s='k9s -n default'
alias restartgraphql='kubectl rollout restart deployment/graphql-gateway'
alias launchapp='pro && java -jar com.car2go.mocks.wsu-4.1.jar'
alias redis_cache='redis-cli -h xxx --tls -a xxx -p 6379'
alias pipelines='mops && cd pipelines'

alias nr='npm run'
alias nrs='nr start'
alias nrd='nr dev'
alias nrt='rm -rf test/generated && nr test'
alias nsf='npx standard --fix'
alias ni='npm install'

alias pg='ping google.de'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
